### ISSUE TITLE
SKU Errors

### ISSUE THREAD

**Issue by jtynch-ws** [mrobinson-ws/azure_comboscript#1]
![image](https://user-images.githubusercontent.com/86434912/127702301-aa5dc9d1-0e79-415f-96da-736b3281ff1a.png)
![image](https://user-images.githubusercontent.com/86434912/127702318-02c9d7b5-ea71-4dfa-aecc-b0ce6ce054e1.png)
![image](https://user-images.githubusercontent.com/86434912/127702331-6672ca74-d971-49b4-bb0a-7eed0d87b7bb.png)

**Comment by mrobinson-ws** [comment]
Added in Version 1.0.2
