### ISSUE TITLE
Check shared vs user mailbox

### ISSUE THREAD

**Issue by smartin2895** [mrobinson-ws/azure_comboscript#10]
Throws an error when trying to add permissions for shared mailboxes.
"PublishingEditor Permissions for jrorie@blah.com on jhales@blah.com:\Calendar\SCH Staff Calendar Not Set"

In this case it turned out that jrorie was a shared mailbox.

**Comment by mrobinson-ws** [comment]
Added check for Shared Mailbox to Mailbox Permissions
