### ISSUE TITLE
Country and State fields in "User Creatations"

### ISSUE THREAD

**Issue by Sean-Urbina** [mrobinson-ws/azure_comboscript#8]
I've noticed that when you create a New User the entry for "Country" is going into the "state" section of the users contact info. Small issue and quick fix.

Line 1135 :  Set-AzureADUser -ObjectID $UPN -State $countryTextbox.Text
change to
Line 1135:  Set-AzureADUser -ObjectID $UPN -Country $countryTextbox.Text

Tested it on a test user already.

**Comment by mrobinson-ws** [comment]
Updated script, will be in next release.  Thanks!
